---
- name: Create a keyring for your cluster and generate a monitor secret key.
  command: ceph-authtool --create-keyring /tmp/ceph.mon.keyring --gen-key -n mon. --cap mon 'allow *'
  become: false

- name: Generate an administrator keyring, generate a client.admin user and add the user to the keyring.
  command: ceph-authtool --create-keyring /etc/ceph/ceph.client.admin.keyring --gen-key -n client.admin --set-uid=0 --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *' --cap mgr 'allow *'
  become: true

- name: Add the client.admin key to the ceph.mon.keyring.
  command: ceph-authtool /tmp/ceph.mon.keyring --import-keyring /etc/ceph/ceph.client.admin.keyring
  become: false

- name: Generate a monitor map using the hostname(s), host IP address(es) and the FSID. Save it as /tmp/monmap
  command: monmaptool --create --add {{ monitor_name }} {{ monitor_address }} --fsid {{ fsid }} /tmp/monmap
  become: false

- name: create (and fix ownership of) monitor directory
  file:
    path: /var/lib/ceph/mon/{{ cluster }}-{{ monitor_name }}
    state: directory
    mode: "0755"
    recurse: true    

- name: Populate the monitor daemon(s) with the monitor map and keyring.
  command: ceph-mon --cluster {{ cluster }} --mkfs -i {{ monitor_name }} --monmap /tmp/monmap --keyring /tmp/ceph.mon.keyring

- name: Mark that the monitor is created and ready to be started
  file:
    path: /var/lib/ceph/mon/{{ cluster }}-{{ monitor_name }}/done
    state: file
