---

- set_fact:
    monitor_name: "{{ ansible_hostname }}"

- name: generate cluster uuid
  local_action: shell uuidgen
  register: cluster_uuid
  become: false

- set_fact:
    fsid: "{{ cluster_uuid.stdout }}"
